config/routes.rb
Spree::Core::Engine.routes.prepend do
  
    match '/spree_cmcic/:gateway_id/:order_id' => 'spree_cmcic#show', :as => :spree_cmcic
end

app/models/spree/billing_integration/cmcic.rb
class Spree::BillingIntegration::Cmcic < Spree::BillingIntegration

end

app/models/spree/order_decoration.rb
module Spree
  Order.class_eval do
    
  attr_accessible :cmcic_sDate

  # Confirmation step not compatible with CM-CIC paiement
  def confirmation_required?
    return "toto"
  end
  
  def cmcic_sDevise
    self.currency
  end
  
  def cmcic_sDate
    self.created_at.strftime("%d/%m/%Y:%H:%M:%S")
  end

  def cmcic_sMontant
    ("%.2f" % self.total) + cmcic_sDevise
  end
  
  def cmcic_sReference
    self.number
  end
  
  def cmcic_email
    self.email
  end

  def cmcic_sTexteLibre
    self.special_instructions.nil? ? "" : self.special_instructions
  end
  
  def cmcic_sNbrEch
    ""
  end
  
  def cmcic_sDateEcheance1
    ""
  end

  def cmcic_sDateEcheance2
    ""
  end

  def cmcic_sDateEcheance3
    ""
  end

  def cmcic_sDateEcheance4
    ""
  end
  
  def cmcic_sMontantEcheance1
    ""
  end

  def cmcic_sMontantEcheance2
    ""
  end

  def cmcic_sMontantEcheance3
    ""
  end

  def cmcic_sMontantEcheance4
    ""
  end
  
  def cmcic_sOptions
    ""
  end

  def cmcic_sMAC_Tpe(oTpe)
    sChaineMAC = [oTpe.sNumero, cmcic_sDate, cmcic_sMontant, cmcic_sReference, cmcic_sTexteLibre, oTpe.sVersion, oTpe.sLangue, oTpe.sCodeSociete, cmcic_email, cmcic_sNbrEch, cmcic_sDateEcheance1, cmcic_sMontantEcheance1, cmcic_sDateEcheance2, cmcic_sMontantEcheance2, cmcic_sDateEcheance3, cmcic_sMontantEcheance3, cmcic_sDateEcheance4, cmcic_sMontantEcheance4, cmcic_sOptions].join("*")
    
    OpenSSL::HMAC.hexdigest(OpenSSL::Digest::Digest.new("sha1"), oTpe.getPackCle, sChaineMAC).upcase
  end  
end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
    
  # Confirmation step not compatible with CM-CIC paiement
  def confirmation_required?
    return false
  end
  
  def cmcic_sDevise
    self.currency
  end
  
  def cmcic_sDate
    self.payment_date.strftime("%d/%m/%Y:%H:%M:%S")
  end

  def cmcic_sMontant
    ("%.2f" % self.total) + cmcic_sDevise
  end
  
  def cmcic_sReference
    self.number
  end
  
  def cmcic_email
    self.email
  end

  def cmcic_sTexteLibre
    self.special_instructions.nil? ? "" : self.special_instructions
  end
  
  def cmcic_sNbrEch
    ""
  end
  
  def cmcic_sDateEcheance1
    ""
  end

  def cmcic_sDateEcheance2
    ""
  end

  def cmcic_sDateEcheance3
    ""
  end

  def cmcic_sDateEcheance4
    ""
  end
  
  def cmcic_sMontantEcheance1
    ""
  end

  def cmcic_sMontantEcheance2
    ""
  end

  def cmcic_sMontantEcheance3
    ""
  end

  def cmcic_sMontantEcheance4
    ""
  end
  
  def cmcic_sOptions
    ""
  end

  def cmcic_sMAC_Tpe(oTpe)
    sChaineMAC = [oTpe.sNumero, cmcic_sDate, cmcic_sMontant, cmcic_sReference, cmcic_sTexteLibre, oTpe.sVersion, oTpe.sLangue, oTpe.sCodeSociete, cmcic_email, cmcic_sNbrEch, cmcic_sDateEcheance1, cmcic_sMontantEcheance1, cmcic_sDateEcheance2, cmcic_sMontantEcheance2, cmcic_sDateEcheance3, cmcic_sMontantEcheance3, cmcic_sDateEcheance4, cmcic_sMontantEcheance4, cmcic_sOptions].join("*")
    
    OpenSSL::HMAC.hexdigest(OpenSSL::Digest::Digest.new("sha1"), oTpe.getPackCle, sChaineMAC).upcase
  end  

end

app/controllers/spree/checkout_controller_decorator.rb
module Spree
  CheckoutController.class_eval do
    before_filter :redirect_to_cmcic_if_needed, :only => [:update]
    
    def redirect_to_cmcic_if_needed
      return unless (params[:state] == "payment")
      return unless params[:order][:payments_attributes]

      payment_method = Spree::PaymentMethod.find(params[:order][:payments_attributes].first[:payment_method_id])
      return unless payment_method.kind_of?(Spree::BillingIntegration::Cmcic)
      
      redirect_to edit_order_checkout_url(@order, :state => 'payment'),
                    :notice => 'Complete CB Paiement !'

    end

  end
end

app/controllers/spree_cmcic_controller.rb
class SpreeCmcicController < ApplicationController
  respond_to :html

  def show
    @order = Spree::Order.find(params[:order_id])
    @gateway = @order.available_payment_methods.find{|x| x.id == params[:gateway_id].to_i }

    if @order.blank? || @gateway.blank?
      flash[:error] = I18n.t('invalid_arguments')
      redirect_to :back
    else
      
      @order.update_attribute(:payment_date, @order.updated_at)

    end
    
    respond_to do |format|
      format.html { render 'show', :layout => false }
    end
  end

end

app/views/spree/checkout/payment/_cmcic.html.erb
<p data-hook="cmcic_checkout"></p>

<%
opts = {}
opts[:transaction_id] = "#{@order.number}"
opts[:amount] = @order.total
opts[:payment_method_id] = payment_method.id
%>

<style>
  iframe.skrill_frame{
    border: 0px;
    width: 500px;
    height: 500px;
  }
</style>

<fieldset id="cmcic_payment__<%= payment_method.id %>" data-hook>
  <legend><%= t(:payment_information) %></legend>

  <iframe id="cmcic_frame_<%= payment_method.id %>"
          class="cmcic_frame" src="<%= spree_cmcic_url(payment_method.id, @order.id) %>"></iframe>
          
</fieldset>

app/views/spree_cmcic/show.html.erb
Show Spree_cmcic 1
<% oTpe = CMCIC_Tpe.new %>
<%= form_tag(oTpe.sUrlPaiement, :method => :post, :target => "_blank") do |f| %>
    <%= hidden_field_tag "version", oTpe.sVersion %>
    <%= hidden_field_tag "TPE", oTpe.sNumero %>
    <%= hidden_field_tag "date", @order.cmcic_sDate %>
    <%= hidden_field_tag "montant", @order.cmcic_sMontant %>
    <%= hidden_field_tag "reference", @order.cmcic_sReference %>
    <%= hidden_field_tag "MAC", @order.cmcic_sMAC_Tpe(oTpe) %>
    <%= hidden_field_tag "url_retour", "http://localhost:3000/store/checkout/payment" %>
    <%= hidden_field_tag "url_retour_ok", "http://localhost:3000/store/checkout/payment" %>
    <%= hidden_field_tag "url_retour_err", "http://localhost:3000/store/checkout/payment" %>
    <%= hidden_field_tag "lgue", oTpe.sLangue %>
    <%= hidden_field_tag "societe", oTpe.sCodeSociete %>
    <%= hidden_field_tag "texte-libre", @order.cmcic_sTexteLibre %>
    <%= hidden_field_tag "mail", @order.cmcic_email %>
    <%= submit_tag "Paiment CB", :class => "btn-blue align-center" %>
<% end %>